# Generated by Django 4.2.3 on 2023-08-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='email_tujuan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
