# Generated by Django 4.2.3 on 2023-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_sendmail_email_tujuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
