# Generated by Django 4.2.3 on 2023-08-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_sendmail_attach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='attach',
            new_name='attachment',
        ),
    ]
