# Generated by Django 4.2.3 on 2023-08-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_rename_attach_sendmail_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmail',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='email_tujuan',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='pesan',
        ),
    ]
