# Generated by Django 4.2.3 on 2023-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_remove_sendmail_attachment_remove_sendmail_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sendmail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='recipient',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
