# Generated by Django 4.2.3 on 2023-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_rename_created_at_sendmail_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sendmail',
            old_name='subject',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='recipient',
        ),
        migrations.AddField(
            model_name='sendmail',
            name='email_tujuan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='pesan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
