# Generated by Django 4.2.3 on 2023-08-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_rename_sent_at_sendmail_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='attachment',
            new_name='lampiran',
        ),
    ]
